import { notFound } from "next/navigation";
import LearnModuleClient from "./LearnModuleClient";

const MODULE_MAP: Record<string, { title: string; prompt: string; minutes: number; category: string }> = {
  "how-ontarios-legislature-works": {
    title: "How Ontario's Legislature Works",
    minutes: 5,
    category: "Systems",
    prompt: "Explain how Ontario's provincial legislature works to a 16-year-old Canadian student. Cover: what the Legislative Assembly is, how MPPs are elected, how laws get passed, and why it matters to everyday life. Be specific to Ontario. Write in clear sections with headers.",
  },
  "ontarios-tax-system": {
    title: "Ontario's Tax System Explained",
    minutes: 5,
    category: "Systems",
    prompt: "",
  },
  "municipal-government": {
    title: "How Municipal Government Works",
    minutes: 4,
    category: "Systems",
    prompt: "",
  },
  "charter-of-rights": {
    title: "What is the Charter of Rights?",
    minutes: 5,
    category: "Systems",
    prompt: "",
  },
  "what-is-anarchism": {
    title: "What is Anarchism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "",
  },
  "what-is-fascism": {
    title: "What is Fascism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "",
  },
  "what-is-social-democracy": {
    title: "What is Social Democracy?",
    minutes: 4,
    category: "Ideologies",
    prompt: "",
  },
  "jagmeet-singh": {
    title: "Jagmeet Singh and the NDP",
    minutes: 5,
    category: "Figures",
    prompt: "",
  },
  "karl-marx": {
    title: "Karl Marx: Ideas and Legacy",
    minutes: 6,
    category: "Figures",
    prompt: "",
  },
  "nelson-mandela": {
    title: "Nelson Mandela and Justice",
    minutes: 6,
    category: "Figures",
    prompt: "",
  },
  "malala-yousafzai": {
    title: "Malala Yousafzai and Education Rights",
    minutes: 5,
    category: "Figures",
    prompt: "",
  },
  "what-does-an-mpp-actually-do": {
    title: "What Does an MPP Actually Do?",
    minutes: 4,
    category: "Systems",
    prompt: "Explain what a Member of Provincial Parliament (MPP) does in Ontario to a 16-year-old. Cover their daily responsibilities, how they represent constituents, how they vote on bills, and how to contact yours. Be specific and practical.",
  },
  "how-a-bill-becomes-law": {
    title: "How a Bill Becomes Law",
    minutes: 5,
    category: "Systems",
    prompt: "Explain step by step how a bill becomes a law in Ontario's provincial legislature. Use a real recent Ontario bill as an example. Write for a 16-year-old, be specific and clear.",
  },
  "what-is-capitalism": {
    title: "What is Capitalism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain capitalism to a 16-year-old Canadian student. Cover: core principles, how it works in practice, its strengths and criticisms, and how it shapes Ontario's economy today. Present it fairly — show both what supporters and critics say.",
  },
  "what-is-socialism": {
    title: "What is Socialism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain socialism to a 16-year-old Canadian student. Cover: core principles, different forms of socialism, real world examples, strengths and criticisms. Present it fairly — show both what supporters and critics say. Include Canadian context.",
  },
  "che-guevara": {
    title: "Che Guevara: Revolutionary or War Criminal?",
    minutes: 7,
    category: "Figures",
    prompt: "Write a balanced profile of Che Guevara for a 16-year-old. Cover his early life, role in the Cuban Revolution, his ideology, the executions he ordered, his legacy, and why people still debate him today. Do not glorify or condemn — present the full picture with evidence.",
  },
  "tommy-douglas": {
    title: "Tommy Douglas and Canadian Healthcare",
    minutes: 5,
    category: "Figures",
    prompt: "Write a profile of Tommy Douglas for a 16-year-old Canadian student. Cover his background, how he brought public healthcare to Saskatchewan, his role in creating Medicare, and his lasting impact on Canada. Include why some opposed him and why he's still relevant today.",
  },
  "provincial-vs-federal-power": {
  title: "Provincial vs Federal Power",
  minutes: 6,
  category: "Systems",
  prompt: "Explain the difference between provincial and federal government powers in Canada to a 16-year-old. Use Ontario as the example. Cover what each level controls, why it matters, and real examples of conflicts between them. Use ## for section headers.",
},
"how-ontarios-budget-works": {
  title: "How Ontario's Budget Works",
  minutes: 7,
  category: "Systems",
  prompt: "Explain how Ontario's provincial budget works to a 16-year-old. Cover how it's made, what it funds, how to read it, and why it affects everyday life. Use ## for section headers.",
},
"what-is-liberalism": {
  title: "What is Liberalism?",
  minutes: 4,
  category: "Ideologies",
  prompt: "Explain liberalism to a 16-year-old Canadian student. Cover core principles, classical vs modern liberalism, Canadian examples, strengths and criticisms. Present both supporter and critic views fairly. Use ## for section headers.",
},
"what-is-conservatism": {
  title: "What is Conservatism?",
  minutes: 4,
  category: "Ideologies",
  prompt: "Explain conservatism to a 16-year-old Canadian student. Cover core principles, different types, Canadian examples, strengths and criticisms. Present both supporter and critic views fairly. Use ## for section headers.",
},
"what-is-marxism": {
  title: "What is Marxism?",
  minutes: 6,
  category: "Ideologies",
  prompt: "Explain Marxism to a 16-year-old Canadian student. Cover Marx's core ideas, historical applications, why it attracts supporters, and its criticisms. Present it fairly without glorifying or dismissing. Use ## for section headers.",
},
"what-is-libertarianism": {
  title: "What is Libertarianism?",
  minutes: 5,
  category: "Ideologies",
  prompt: "Explain libertarianism to a 16-year-old Canadian student. Cover core principles, economic and social libertarianism, Canadian context, strengths and criticisms. Present both supporter and critic views fairly. Use ## for section headers.",
},
"pierre-trudeau": {
  title: "Pierre Trudeau and the Charter",
  minutes: 6,
  category: "Figures",
  prompt: "Write a profile of Pierre Trudeau for a 16-year-old Canadian student. Cover his background, major policies, the Charter of Rights and Freedoms, controversies like the War Measures Act, and his lasting impact on Canada. Use ## for section headers.",
},
"margaret-thatcher": {
  title: "Margaret Thatcher and Neoliberalism",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Margaret Thatcher for a 16-year-old. Cover her background, economic policies, privatization, the Falklands War, her legacy, and why she's still debated today. Present both supporter and critic views. Use ## for section headers.",
},
"doug-ford": {
  title: "Doug Ford: Policies and Controversies",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Doug Ford as Ontario Premier for a 16-year-old. Cover his background, major policies, controversies like Greenbelt, education cuts, healthcare changes, and how different Ontarians view him. Present both supporter and critic views fairly. Use ## for section headers.",
},
"donald-trump": {
  title: "Donald Trump: Rise and Impact",
  minutes: 7,
  category: "Figures",
  prompt: "Write a balanced profile of Donald Trump for a 16-year-old. Cover his background, 2016 and 2024 election wins, major policies, controversies, and how he changed American politics. Present both supporter and critic views fairly. Use ## for section headers.",
},
"barack-obama": {
  title: "Barack Obama and American Politics",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Barack Obama for a 16-year-old. Cover his background, major policies like the ACA, foreign policy, his historic significance, and criticisms. Present both supporter and critic views. Use ## for section headers.",
},
"justin-trudeau": {
  title: "Justin Trudeau: Legacy and Criticism",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Justin Trudeau for a 16-year-old Canadian student. Cover his time as PM, major policies, controversies like SNC-Lavalin and blackface, his resignation, and how Canadians view his legacy. Use ## for section headers.",
},
"angela-merkel": {
  title: "Angela Merkel and European Leadership",
  minutes: 5,
  category: "Figures",
  prompt: "Write a balanced profile of Angela Merkel for a 16-year-old. Cover her background, 16 years as German Chancellor, refugee policy, European leadership, and her legacy. Use ## for section headers.",
},
"fidel-castro": {
  title: "Fidel Castro: Cuba's Controversial Leader",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Fidel Castro for a 16-year-old. Cover his revolution, communist Cuba, human rights record, US relations, and why he's still debated today. Present both supporter and critic views. Use ## for section headers.",
},
"mahatma-gandhi": {
  title: "Gandhi and Non-Violent Resistance",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Mahatma Gandhi for a 16-year-old. Cover his methods of non-violent resistance, Indian independence, his views on caste, and his global legacy. Use ## for section headers.",
},
"martin-luther-king": {
  title: "Martin Luther King Jr. and Civil Rights",
  minutes: 6,
  category: "Figures",
  prompt: "Write a profile of Martin Luther King Jr. for a 16-year-old. Cover the Civil Rights Movement, his methods, major speeches, FBI surveillance, assassination, and lasting impact. Use ## for section headers.",
},
"aoc": {
  title: "Alexandria Ocasio-Cortez and Progressive Politics",
  minutes: 5,
  category: "Figures",
  prompt: "Write a balanced profile of Alexandria Ocasio-Cortez for a 16-year-old. Cover her background, Green New Deal, democratic socialism, impact on the Democratic Party, and criticisms. Use ## for section headers.",
},
"winston-churchill": {
  title: "Winston Churchill: Hero or Villain?",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Winston Churchill for a 16-year-old. Cover WWII leadership, the Bengal famine, colonial policies, and why historians still debate his legacy. Present both sides fairly. Use ## for section headers.",
},
"vladimir-putin": {
  title: "Vladimir Putin and Russian Power",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Vladimir Putin for a 16-year-old. Cover his rise to power, political system, Ukraine invasion, human rights record, and how Russians vs the West view him. Use ## for section headers.",
},
"supreme-court": {
  title: "How the Supreme Court Works",
  minutes: 5,
  category: "Systems",
  prompt: "Explain how Canada's Supreme Court works to a 16-year-old. Cover how judges are appointed, how cases reach the court, landmark Canadian rulings, and why it matters. Use ## for section headers.",
},
"notwithstanding-clause": {
  title: "What is the Notwithstanding Clause?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain the notwithstanding clause (Section 33 of the Charter) to a 16-year-old. Cover what it does, how Ontario and Quebec have used it, the debate around it, and why it matters. Use ## for section headers.",
},
"ontario-healthcare-system": {
  title: "How Ontario's Healthcare System Works",
  minutes: 6,
  category: "Systems",
  prompt: "Explain how Ontario's healthcare system works to a 16-year-old. Cover OHIP, what's covered and what isn't, how hospitals are funded, current challenges, and the privatization debate. Use ## for section headers.",
},
"what-is-lobbying": {
  title: "What is Lobbying?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain lobbying to a 16-year-old Canadian student. Cover what lobbyists do, Ontario examples, why it's legal, arguments for and against, and how it affects policy. Use ## for section headers.",
},
"media-and-politics": {
  title: "How Media Shapes Politics",
  minutes: 5,
  category: "Systems",
  prompt: "Explain how media shapes politics to a 16-year-old. Cover traditional vs social media, media bias, the Ontario media landscape, misinformation, and how to be a critical news consumer. Use ## for section headers.",
},
"gerrymandering": {
  title: "What is Gerrymandering?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain gerrymandering to a 16-year-old. Cover how it works, US vs Canadian examples, why Canada is less affected, and why electoral boundaries still matter. Use ## for section headers.",
},
"political-parties": {
  title: "How Political Parties Work",
  minutes: 5,
  category: "Systems",
  prompt: "Explain how political parties work in Ontario and Canada to a 16-year-old. Cover party structure, how leaders are chosen, party platforms, whipped votes, and Ontario's main parties. Use ## for section headers.",
},
"what-is-referendum": {
  title: "What is a Referendum?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain what a referendum is to a 16-year-old. Cover how they work in Canada, examples like Quebec and electoral reform votes, pros and cons of direct democracy. Use ## for section headers.",
},
"federal-government": {
  title: "How Canada's Federal Government Works",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain how Canada's federal government works to a 16-year-old. Cover the House of Commons, Senate, Governor General, how laws are passed, and how it differs from provincial government. Use ## for section headers.",
},
"prime-minister-role": {
  title: "What Does the Prime Minister Actually Do?",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain what Canada's Prime Minister actually does to a 16-year-old. Cover their powers, limits, Cabinet, relationship with Parliament, and how they compare to a US President. Use ## for section headers.",
},
"canadas-senate": {
  title: "Canada's Senate: What's the Point?",
  minutes: 4,
  category: "Canada & World",
  prompt: "Explain Canada's Senate to a 16-year-old. Cover how senators are appointed, what they do, controversies like the expenses scandal, and the debate over abolishing or reforming it. Use ## for section headers.",
},
"first-nations-politics": {
  title: "First Nations and Canadian Politics",
  minutes: 7,
  category: "Canada & World",
  prompt: "Explain the relationship between First Nations and Canadian politics to a 16-year-old. Cover treaties, residential schools, land rights, UNDRIP, current political issues, and reconciliation. Be respectful and factual. Use ## for section headers.",
},
"canada-immigration": {
  title: "Canada's Immigration System",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain Canada's immigration system to a 16-year-old. Cover the points system, refugee claims, temporary workers, Ontario's demographics, and the current political debate around immigration levels. Use ## for section headers.",
},
"united-nations": {
  title: "The UN: What Does It Actually Do?",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain the United Nations to a 16-year-old. Cover its structure, what it actually does vs what people think it does, its failures and successes, and Canada's role. Use ## for section headers.",
},
"nato-canada": {
  title: "NATO and Why Canada Is In It",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain NATO to a 16-year-old Canadian student. Cover what it is, why Canada joined, the 2% spending debate, Russia-Ukraine context, and arguments for and against Canadian membership. Use ## for section headers.",
},
"canadian-elections": {
  title: "How Elections Work in Canada",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain how Canadian federal and provincial elections work to a 16-year-old. Cover the first-past-the-post system, why parties with fewer votes can win, voter turnout, and how to vote when you turn 18. Use ## for section headers.",
},
"commonwealth": {
  title: "What is the Commonwealth?",
  minutes: 4,
  category: "Canada & World",
  prompt: "Explain the Commonwealth of Nations to a 16-year-old Canadian student. Cover what it is, its colonial origins, what it does today, Canada's role, and whether it's still relevant. Use ## for section headers.",
},
"canada-us-relations": {
  title: "Canada-US Relations Explained",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain Canada-US relations to a 16-year-old. Cover trade, CUSMA, border issues, cultural influence, Trump-era tensions, and why the relationship is both essential and complicated. Use ## for section headers.",
},
"what-is-colonialism": {
  title: "What is Colonialism?",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain colonialism to a 16-year-old Canadian student. Cover what it is, British and French colonialism in Canada, its lasting effects on Indigenous peoples and global south, and why it's still relevant today. Use ## for section headers.",
},
"israel-palestine": {
  title: "The Israeli-Palestinian Conflict",
  minutes: 7,
  category: "Canada & World",
  prompt: "Explain the Israeli-Palestinian conflict to a 16-year-old. Cover the history, key events, both sides' perspectives, Canada's position, and why it's so divisive. Be strictly factual and balanced — do not take sides. Use ## for section headers.",
},
"russia-ukraine": {
  title: "Russia-Ukraine War: Background",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain the Russia-Ukraine war to a 16-year-old Canadian student. Cover historical background, why Russia invaded, Ukraine's response, Canada's involvement, and the global impact. Be factual and balanced. Use ## for section headers.",
},
"china-politics": {
  title: "China's Political System",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain China's political system to a 16-year-old. Cover the Communist Party structure, how it differs from Western democracy, economic model, human rights issues, and Canada-China relations. Use ## for section headers.",
},
"what-is-g7": {
  title: "What is the G7?",
  minutes: 4,
  category: "Canada & World",
  prompt: "Explain the G7 to a 16-year-old Canadian student. Cover what it is, who's in it, what it does, Canada's role, and criticisms of it. Use ## for section headers.",
},
"climate-change-politics": {
  title: "Climate Change and Politics",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the politics of climate change to a 16-year-old Canadian student. Cover the science consensus, carbon tax debate, Ontario's policies, international agreements, and left vs right perspectives. Use ## for section headers.",
},
"universal-basic-income": {
  title: "What is Universal Basic Income?",
  minutes: 5,
  category: "Issues",
  prompt: "Explain Universal Basic Income to a 16-year-old. Cover what it is, Ontario's pilot program, arguments for and against, cost concerns, and political positions. Use ## for section headers.",
},
"drug-policy-canada": {
  title: "Drug Policy in Canada",
  minutes: 5,
  category: "Issues",
  prompt: "Explain drug policy in Canada to a 16-year-old. Cover cannabis legalization, opioid crisis, decriminalization debate, harm reduction, and different political positions. Use ## for section headers.",
},
"gun-control": {
  title: "Gun Control: Canada vs US",
  minutes: 5,
  category: "Issues",
  prompt: "Explain the gun control debate to a 16-year-old, comparing Canada and the US. Cover Canadian laws, recent changes, the US Second Amendment, and why the debate differs so much between the two countries. Use ## for section headers.",
},
"abortion-rights": {
  title: "Abortion Rights and Politics",
  minutes: 6,
  category: "Issues",
  prompt: "Explain abortion rights and politics to a 16-year-old. Cover Canada's legal status, how it differs from the US post-Roe, different moral and political positions, and the Ontario political landscape. Present all perspectives fairly. Use ## for section headers.",
},
"police-reform": {
  title: "Police Reform and Defunding Debate",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the police reform debate to a 16-year-old. Cover what defunding actually means, Ontario context, arguments for and against reform, race and policing data, and different political positions. Use ## for section headers.",
},
"free-speech": {
  title: "Free Speech vs Hate Speech",
  minutes: 5,
  category: "Issues",
  prompt: "Explain the free speech vs hate speech debate to a 16-year-old Canadian student. Cover Charter protections, what hate speech laws actually say, campus debates, online speech, and different political positions. Use ## for section headers.",
},
"income-inequality": {
  title: "Income Inequality in Ontario",
  minutes: 5,
  category: "Issues",
  prompt: "Explain income inequality in Ontario to a 16-year-old. Cover the data, causes, effects on daily life, what different political parties propose, and why it's gotten worse. Use ## for section headers.",
},
"healthcare-privatization": {
  title: "Healthcare Privatization Debate",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the healthcare privatization debate in Ontario to a 16-year-old. Cover what privatization means in this context, Doug Ford's changes, arguments for and against, and what's at stake. Use ## for section headers.",
},
"social-media-democracy": {
  title: "Social Media and Democracy",
  minutes: 5,
  category: "Issues",
  prompt: "Explain how social media affects democracy to a 16-year-old. Cover misinformation, echo chambers, political ads, TikTok and elections, and what Canada is doing about it. Use ## for section headers.",
},
"affirmative-action": {
  title: "What is Affirmative Action?",
  minutes: 5,
  category: "Issues",
  prompt: "Explain affirmative action to a 16-year-old. Cover what it is, US vs Canadian approaches, equity vs equality debate, arguments for and against, and Ontario context. Use ## for section headers.",
},
"prison-reform": {
  title: "Prison System and Reform",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the prison system and reform debate to a 16-year-old Canadian student. Cover how Canadian prisons work, incarceration rates, Indigenous overrepresentation, rehabilitation vs punishment debate. Use ## for section headers.",
},
"rent-control": {
  title: "Rent Control Debate",
  minutes: 5,
  category: "Issues",
  prompt: "Explain the rent control debate to a 16-year-old Ontarian. Cover what rent control is, Ontario's rules, Doug Ford's 2018 changes, economist arguments against it, tenant arguments for it. Use ## for section headers.",
},
"minimum-wage-economics": {
  title: "Minimum Wage Economics",
  minutes: 5,
  category: "Issues",
  prompt: "Explain minimum wage economics to a 16-year-old. Cover Ontario's history, arguments for raising it, business arguments against, what the research actually says, and current political positions. Use ## for section headers.",
},
"electoral-reform": {
  title: "Electoral Reform in Canada",
  minutes: 5,
  category: "Issues",
  prompt: "Explain electoral reform in Canada to a 16-year-old. Cover first-past-the-post, proportional representation, Trudeau's broken promise, Ontario's 2007 referendum, and arguments for and against change. Use ## for section headers.",
},
// Systems additions
  "cabinet-government": {
    title: "How Cabinet Government Works",
    minutes: 5,
    category: "Systems",
    prompt: "Explain how cabinet government works in Ontario and Canada to a 16-year-old. Cover what cabinet is, how ministers are chosen, cabinet solidarity, and real examples. Use ## for section headers.",
  },
  "governor-general": {
    title: "What is the Governor General?",
    minutes: 4,
    category: "Systems",
    prompt: "Explain the role of the Governor General to a 16-year-old Canadian student. Cover the history, ceremonial vs real powers, controversies, and whether the role is still relevant. Use ## for section headers.",
  },
  "minority-governments": {
    title: "How Minority Governments Work",
    minutes: 5,
    category: "Systems",
    prompt: "Explain minority governments to a 16-year-old Canadian student. Cover what they are, how they survive, confidence votes, supply and confidence agreements, and Canadian examples. Use ## for section headers.",
  },
  "prorogation": {
    title: "What is Prorogation?",
    minutes: 4,
    category: "Systems",
    prompt: "Explain prorogation to a 16-year-old Canadian student. Cover what it means, when it happens, the 2008 Harper controversy, and arguments about its democratic legitimacy. Use ## for section headers.",
  },
  "public-services-funding": {
    title: "How Public Services Are Funded",
    minutes: 5,
    category: "Systems",
    prompt: "Explain how public services are funded in Ontario to a 16-year-old. Cover taxes, transfer payments, federal-provincial splits, and why some services are underfunded. Use ## for section headers.",
  },
  "ombudsman": {
    title: "What is the Ombudsman?",
    minutes: 4,
    category: "Systems",
    prompt: "Explain what an ombudsman does to a 16-year-old Canadian student. Cover Ontario's ombudsman, how to file a complaint, real cases, and why the role matters. Use ## for section headers.",
  },
  "auditor-general": {
    title: "How Auditor Generals Work",
    minutes: 4,
    category: "Systems",
    prompt: "Explain the role of the Auditor General to a 16-year-old Canadian student. Cover federal and provincial versions, what they audit, recent findings, and why they matter for accountability. Use ## for section headers.",
  },
  "coalition-government": {
    title: "What is a Coalition Government?",
    minutes: 5,
    category: "Systems",
    prompt: "Explain coalition governments to a 16-year-old Canadian student. Cover what they are, how they form, Canadian and international examples, and pros and cons compared to majority governments. Use ## for section headers.",
  },
  "question-period": {
    title: "How Question Period Works",
    minutes: 4,
    category: "Systems",
    prompt: "Explain Question Period to a 16-year-old Canadian student. Cover what it is, how it works in Ottawa and Queen's Park, whether it actually holds government accountable, and famous moments. Use ## for section headers.",
  },
  // Ideologies additions
  "what-is-nationalism": {
    title: "What is Nationalism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain nationalism to a 16-year-old Canadian student. Cover core principles, different types, Quebec nationalism, dangerous forms, and how it shapes politics today. Present fairly. Use ## for section headers.",
  },
  "what-is-populism": {
    title: "What is Populism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain populism to a 16-year-old Canadian student. Cover what it means, left vs right populism, Canadian examples like Doug Ford and Jagmeet Singh, and why it's rising globally. Use ## for section headers.",
  },
  "what-is-feminism": {
    title: "What is Feminism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain feminism to a 16-year-old Canadian student. Cover the waves of feminism, core principles, intersectionality, Canadian context, and different political positions on it. Present fairly. Use ## for section headers.",
  },
  "what-is-green-politics": {
    title: "What is Green Politics?",
    minutes: 4,
    category: "Ideologies",
    prompt: "Explain green politics and environmentalism as a political ideology to a 16-year-old Canadian student. Cover core principles, Green Party of Canada, ecosocialism, and tensions with economic growth. Use ## for section headers.",
  },
  "what-is-neoliberalism": {
    title: "What is Neoliberalism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain neoliberalism to a 16-year-old Canadian student. Cover its core ideas, how it shaped policy from the 1980s onward, Canadian examples, and critiques from left and right. Use ## for section headers.",
  },
  "what-is-communism": {
    title: "What is Communism?",
    minutes: 6,
    category: "Ideologies",
    prompt: "Explain communism to a 16-year-old Canadian student. Cover Marx and Engels, how it differs from socialism, real world applications in USSR and China, why it failed or succeeded in different places, and modern relevance. Present fairly. Use ## for section headers.",
  },
  "what-is-authoritarianism": {
    title: "What is Authoritarianism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain authoritarianism to a 16-year-old. Cover what defines it, different types, modern examples, how democracies slide into it, and warning signs. Use ## for section headers.",
  },
  "what-is-progressivism": {
    title: "What is Progressivism?",
    minutes: 4,
    category: "Ideologies",
    prompt: "Explain progressivism to a 16-year-old Canadian student. Cover core beliefs, how it differs from liberalism, Canadian progressive movements, and criticisms from both left and right. Use ## for section headers.",
  },
  "what-is-classical-liberalism": {
    title: "What is Classical Liberalism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain classical liberalism to a 16-year-old Canadian student. Cover its origins, core thinkers like Locke and Mill, how it differs from modern liberalism, and its influence on Canadian politics. Use ## for section headers.",
  },
  "what-is-christian-democracy": {
    title: "What is Christian Democracy?",
    minutes: 4,
    category: "Ideologies",
    prompt: "Explain Christian democracy to a 16-year-old. Cover its origins in Europe, core values, how it differs from theocracy, and its influence on Canadian conservative politics. Use ## for section headers.",
  },
  "what-is-technocracy": {
    title: "What is Technocracy?",
    minutes: 4,
    category: "Ideologies",
    prompt: "Explain technocracy to a 16-year-old. Cover what it means, arguments for rule by experts, democratic objections, and modern examples like central banks and COVID policy. Use ## for section headers.",
  },
  // Figures additions
  "mao-zedong": {
    title: "Mao Zedong and Modern China",
    minutes: 7,
    category: "Figures",
    prompt: "Write a balanced profile of Mao Zedong for a 16-year-old. Cover the Long March, founding of the PRC, the Great Leap Forward, Cultural Revolution, death toll estimates, and his contested legacy in China today. Do not glorify or condemn — present evidence. Use ## for section headers.",
  },
  "simone-de-beauvoir": {
    title: "Simone de Beauvoir and Political Feminism",
    minutes: 5,
    category: "Figures",
    prompt: "Write a profile of Simone de Beauvoir for a 16-year-old. Cover her life, The Second Sex, existentialist feminism, her influence on women's rights movements, and her relevance today. Use ## for section headers.",
  },
  "lester-pearson": {
    title: "Lester B. Pearson and Canadian Peacekeeping",
    minutes: 5,
    category: "Figures",
    prompt: "Write a profile of Lester B. Pearson for a 16-year-old Canadian student. Cover his Nobel Peace Prize, invention of UN peacekeeping, Medicare groundwork, flag debate, and his legacy. Use ## for section headers.",
  },
  "rosa-parks": {
    title: "Rosa Parks and the Civil Rights Movement",
    minutes: 5,
    category: "Figures",
    prompt: "Write a profile of Rosa Parks for a 16-year-old. Cover her act of resistance, the Montgomery Bus Boycott, her broader activism beyond the bus, and her legacy. Avoid oversimplifying her story. Use ## for section headers.",
  },
  "john-a-macdonald": {
    title: "John A. Macdonald: Father and Controversies",
    minutes: 6,
    category: "Figures",
    prompt: "Write a balanced profile of John A. Macdonald for a 16-year-old Canadian student. Cover Confederation, the CPR, the Indian Act, residential schools, and the modern debate about his statues and legacy. Do not glorify or condemn — present the full picture. Use ## for section headers.",
  },
  "mark-carney": {
    title: "Mark Carney and Economic Policy",
    minutes: 5,
    category: "Figures",
    prompt: "Write a profile of Mark Carney for a 16-year-old Canadian student. Cover his role as Bank of Canada governor, Bank of England governor, his climate finance work, and his entry into Canadian politics. Use ## for section headers.",
  },
  // Canada & World additions
  "truth-and-reconciliation": {
    title: "Truth and Reconciliation in Canada",
    minutes: 7,
    category: "Canada & World",
    prompt: "Explain truth and reconciliation in Canada to a 16-year-old. Cover the TRC, 94 calls to action, residential schools, unmarked graves, and what reconciliation actually means in practice. Be factual and respectful. Use ## for section headers.",
  },
  "world-bank": {
    title: "What is the World Bank?",
    minutes: 5,
    category: "Canada & World",
    prompt: "Explain the World Bank to a 16-year-old. Cover what it does, how it's structured, Canada's role, criticisms about debt dependency, and its actual impact on developing countries. Use ## for section headers.",
  },
  "imf": {
    title: "How the IMF Works",
    minutes: 5,
    category: "Canada & World",
    prompt: "Explain the International Monetary Fund to a 16-year-old. Cover its purpose, how it lends money, structural adjustment programs, criticisms, and Canada's role. Use ## for section headers.",
  },
  "cusma-nafta": {
    title: "What is CUSMA/NAFTA?",
    minutes: 5,
    category: "Canada & World",
    prompt: "Explain NAFTA and its replacement CUSMA to a 16-year-old Canadian student. Cover what free trade agreements do, winners and losers, Trump's renegotiation, and what it means for Ontario workers. Use ## for section headers.",
  },
  "canada-afghanistan": {
    title: "Canada's Role in Afghanistan",
    minutes: 6,
    category: "Canada & World",
    prompt: "Explain Canada's military role in Afghanistan to a 16-year-old. Cover why Canada joined, what soldiers did, the casualties, the 2021 Taliban takeover, and the debate about whether it was worth it. Use ## for section headers.",
  },
  "paris-agreement": {
    title: "What is the Paris Agreement?",
    minutes: 5,
    category: "Canada & World",
    prompt: "Explain the Paris Agreement to a 16-year-old Canadian student. Cover what it commits countries to, how Canada is doing on its targets, criticisms from both left and right, and what happens if targets are missed. Use ## for section headers.",
  },
  "india-politics": {
    title: "India's Political System",
    minutes: 6,
    category: "Canada & World",
    prompt: "Explain India's political system to a 16-year-old. Cover its democracy, Modi and the BJP, Hindu nationalism, Canada-India relations and the Nijjar affair, and why India matters geopolitically. Use ## for section headers.",
  },
  "european-union": {
    title: "The European Union Explained",
    minutes: 6,
    category: "Canada & World",
    prompt: "Explain the European Union to a 16-year-old. Cover how it works, the Euro, Brexit, democratic deficit criticisms, and why it matters to Canada. Use ## for section headers.",
  },
  "what-is-brics": {
    title: "What is BRICS?",
    minutes: 5,
    category: "Canada & World",
    prompt: "Explain BRICS to a 16-year-old. Cover what countries are in it, why it formed, its challenge to Western-dominated institutions, recent expansion, and what it means for Canada. Use ## for section headers.",
  },
  "north-korea": {
    title: "North Korea: What's Actually Going On?",
    minutes: 6,
    category: "Canada & World",
    prompt: "Explain North Korea to a 16-year-old. Cover the Kim dynasty, why the regime survives, nuclear weapons program, humanitarian situation, and Canada's position. Be factual. Use ## for section headers.",
  },
  // Issues additions
  "housing-crisis-ontario": {
    title: "Housing Crisis in Ontario",
    minutes: 6,
    category: "Issues",
    prompt: "Explain Ontario's housing crisis to a 16-year-old. Cover why housing is so expensive, zoning laws, developer influence, Doug Ford's policies, and what different parties propose. Use ## for section headers.",
  },
  "student-debt-tuition": {
    title: "Student Debt and Tuition Policy",
    minutes: 5,
    category: "Issues",
    prompt: "Explain student debt and tuition policy to a 16-year-old Ontario student. Cover Ontario tuition history, OSAP, free tuition debates, and different political positions. Use ## for section headers.",
  },
  "trans-rights-politics": {
    title: "Trans Rights and Politics",
    minutes: 6,
    category: "Issues",
    prompt: "Explain trans rights as a political issue to a 16-year-old Canadian student. Cover current legal protections, school policy debates, different political positions, and Ontario context. Present all perspectives fairly and respectfully. Use ## for section headers.",
  },
  "indigenous-land-rights": {
    title: "Indigenous Land Rights",
    minutes: 7,
    category: "Issues",
    prompt: "Explain Indigenous land rights in Canada to a 16-year-old. Cover treaties, unceded land, land back movement, resource development conflicts, and court rulings. Be factual and respectful. Use ## for section headers.",
  },
  "carbon-tax": {
    title: "Carbon Tax: For and Against",
    minutes: 5,
    category: "Issues",
    prompt: "Explain the carbon tax debate to a 16-year-old Canadian student. Cover how it works, the rebate, economic arguments for it, Conservative arguments against it, and what the evidence says. Use ## for section headers.",
  },
  "maid-canada": {
    title: "Euthanasia and MAID in Canada",
    minutes: 6,
    category: "Issues",
    prompt: "Explain Medical Assistance in Dying (MAID) in Canada to a 16-year-old. Cover the law, eligibility, expansion controversies, religious and disability rights objections, and different political positions. Present fairly. Use ## for section headers.",
  },
  "media-bias": {
    title: "Media Bias and How to Spot It",
    minutes: 5,
    category: "Issues",
    prompt: "Explain media bias to a 16-year-old Canadian student. Cover types of bias, how to evaluate sources, Canadian media ownership concentration, and practical tips for being a critical news consumer. Use ## for section headers.",
  },
  "misinformation-democracy": {
    title: "Misinformation and Democracy",
    minutes: 5,
    category: "Issues",
    prompt: "Explain how misinformation affects democracy to a 16-year-old. Cover what misinformation is, how it spreads on social media, Canadian examples, platform responsibility, and what you can do. Use ## for section headers.",
  },
  "online-privacy": {
    title: "Online Privacy and Surveillance",
    minutes: 5,
    category: "Issues",
    prompt: "Explain online privacy and government surveillance to a 16-year-old Canadian student. Cover data collection, Bill C-26, Five Eyes, social media data, and what privacy rights Canadians actually have. Use ## for section headers.",
  },
  "ai-and-politics": {
    title: "AI and Political Power",
    minutes: 5,
    category: "Issues",
    prompt: "Explain how AI intersects with political power to a 16-year-old. Cover deepfakes, AI in elections, surveillance states, job displacement and policy responses, and Canada's AI regulations. Use ## for section headers.",
  },
  // Economy category
  "how-inflation-works": {
    title: "How Inflation Works",
    minutes: 5,
    category: "Economy",
    prompt: "Explain inflation to a 16-year-old Canadian student. Cover what causes it, how the Bank of Canada measures it, how it affects everyday life, and what interest rate hikes actually do. Use ## for section headers.",
  },
  "bank-of-canada": {
    title: "What is the Bank of Canada?",
    minutes: 5,
    category: "Economy",
    prompt: "Explain the Bank of Canada to a 16-year-old. Cover what it does, how it's different from regular banks, interest rate decisions, and why it matters to housing and inflation. Use ## for section headers.",
  },
  "interest-rates": {
    title: "How Interest Rates Affect You",
    minutes: 5,
    category: "Economy",
    prompt: "Explain interest rates to a 16-year-old Canadian student. Cover how they work, how the Bank of Canada sets them, their effect on mortgages and rent, and the inflation-employment tradeoff. Use ## for section headers.",
  },
  "what-is-recession": {
    title: "What is a Recession?",
    minutes: 4,
    category: "Economy",
    prompt: "Explain recessions to a 16-year-old Canadian student. Cover the definition, causes, historical Canadian examples, government responses, and how recessions affect young people. Use ## for section headers.",
  },
  "trade-deficits": {
    title: "How Trade Deficits Work",
    minutes: 5,
    category: "Economy",
    prompt: "Explain trade deficits to a 16-year-old Canadian student. Cover what they are, whether they're actually bad, Canada's trade balance, and how tariffs affect them. Use ## for section headers.",
  },
  "what-is-gdp": {
    title: "What is GDP?",
    minutes: 4,
    category: "Economy",
    prompt: "Explain GDP to a 16-year-old Canadian student. Cover what it measures, what it misses, how Canada's GDP compares globally, and alternative measures like happiness indexes. Use ## for section headers.",
  },
  "government-debt": {
    title: "How Government Debt Works",
    minutes: 5,
    category: "Economy",
    prompt: "Explain government debt to a 16-year-old Canadian student. Cover federal and Ontario debt, how governments borrow, whether debt is always bad, and different political positions. Use ## for section headers.",
  },
  "what-is-austerity": {
    title: "What is Austerity?",
    minutes: 5,
    category: "Economy",
    prompt: "Explain austerity to a 16-year-old. Cover what it means, historical examples, Ontario examples under Harris and Ford, arguments for and against, and what the evidence says about its effectiveness. Use ## for section headers.",
  },
  "taxes-public-services": {
    title: "How Taxes Fund Public Services",
    minutes: 5,
    category: "Economy",
    prompt: "Explain how taxes fund public services to a 16-year-old Ontarian. Cover income tax, sales tax, where money goes, why some services are cut, and the debate about tax levels. Use ## for section headers.",
  },
  "quantitative-easing": {
    title: "What is Quantitative Easing?",
    minutes: 5,
    category: "Economy",
    prompt: "Explain quantitative easing to a 16-year-old. Cover what it is, why central banks use it, how Canada used it during COVID, criticisms about inflation and inequality, and whether it worked. Use ## for section headers.",
  },
  "gig-economy": {
    title: "Gig Economy and Worker Rights",
    minutes: 5,
    category: "Economy",
    prompt: "Explain the gig economy to a 16-year-old Canadian student. Cover what it is, platforms like Uber and DoorDash, worker classification debate, Ontario legislation, and union arguments. Use ## for section headers.",
  },
  "living-wage": {
    title: "What is a Living Wage?",
    minutes: 4,
    category: "Economy",
    prompt: "Explain the concept of a living wage to a 16-year-old Ontarian. Cover how it differs from minimum wage, Ontario living wage calculations, business objections, and political positions. Use ## for section headers.",
  },
  "supply-chains-politics": {
    title: "How Supply Chains Affect Politics",
    minutes: 5,
    category: "Economy",
    prompt: "Explain supply chains and their political impact to a 16-year-old. Cover COVID disruptions, Canada-China dependencies, reshoring debates, and how supply chains affect everyday prices. Use ## for section headers.",
  },
  "corporate-tax": {
    title: "Corporate Tax and Loopholes",
    minutes: 5,
    category: "Economy",
    prompt: "Explain corporate taxes and loopholes to a 16-year-old Canadian student. Cover how corporate tax works, tax havens, Canadian examples, arguments for lower vs higher corporate tax, and recent global minimum tax efforts. Use ## for section headers.",
  },
  "economic-nationalism": {
    title: "What is Economic Nationalism?",
    minutes: 5,
    category: "Economy",
    prompt: "Explain economic nationalism to a 16-year-old. Cover what it means, tariffs, Trump's trade war and Canada's response, Buy Canadian debates, and arguments for and against. Use ## for section headers.",
  },
  // History category
  "cold-war": {
    title: "The Cold War Explained",
    minutes: 7,
    category: "History",
    prompt: "Explain the Cold War to a 16-year-old Canadian student. Cover the US-USSR rivalry, proxy wars, nuclear tension, Canada's role, and how it ended. Use ## for section headers.",
  },
  "ww2-politics": {
    title: "How World War II Changed Politics",
    minutes: 7,
    category: "History",
    prompt: "Explain how World War II changed global politics to a 16-year-old. Cover the UN, decolonization, the welfare state, Canada's role, and the world order it created. Use ## for section headers.",
  },
  "civil-rights-movement": {
    title: "The Civil Rights Movement",
    minutes: 6,
    category: "History",
    prompt: "Explain the American Civil Rights Movement to a 16-year-old. Cover key events, leaders, legislation achieved, Canada's parallel movements, and its ongoing relevance. Use ## for section headers.",
  },
  "fall-of-soviet-union": {
    title: "The Fall of the Soviet Union",
    minutes: 6,
    category: "History",
    prompt: "Explain the fall of the Soviet Union to a 16-year-old. Cover why it collapsed, Gorbachev's reforms, what happened after, and how it shaped today's Russia and Ukraine conflict. Use ## for section headers.",
  },
  "canada-ww1": {
    title: "Canada's Role in World War I",
    minutes: 5,
    category: "History",
    prompt: "Explain Canada's role in World War I to a 16-year-old. Cover why Canada joined, Vimy Ridge, conscription crisis, Indigenous soldiers, and how the war changed Canada's identity. Use ## for section headers.",
  },
  "october-crisis": {
    title: "The October Crisis of 1970",
    minutes: 5,
    category: "History",
    prompt: "Explain the October Crisis of 1970 to a 16-year-old Canadian student. Cover the FLQ, the kidnappings, Trudeau's War Measures Act, civil liberties debate, and its legacy. Use ## for section headers.",
  },
  "apartheid": {
    title: "Apartheid in South Africa",
    minutes: 6,
    category: "History",
    prompt: "Explain apartheid in South Africa to a 16-year-old. Cover what it was, how it worked, the resistance movement, Mandela, Canada's role in sanctions, and the transition to democracy. Use ## for section headers.",
  },
  "french-revolution": {
    title: "The French Revolution and Democracy",
    minutes: 6,
    category: "History",
    prompt: "Explain the French Revolution to a 16-year-old and connect it to modern democracy. Cover causes, key events, the Terror, Napoleon, and how it shaped democratic ideals worldwide. Use ## for section headers.",
  },
  "rwandan-genocide": {
    title: "The Rwandan Genocide",
    minutes: 6,
    category: "History",
    prompt: "Explain the Rwandan genocide to a 16-year-old. Cover the colonial roots of Hutu-Tutsi division, the 1994 genocide, the world's failure to intervene, General Roméo Dallaire's role, and lessons learned. Be factual and respectful. Use ## for section headers.",
  },
  "holocaust-human-rights": {
    title: "How the Holocaust Shaped Human Rights",
    minutes: 7,
    category: "History",
    prompt: "Explain how the Holocaust shaped international human rights to a 16-year-old. Cover the genocide, Nuremberg trials, Universal Declaration of Human Rights, and how it changed international law. Be factual and respectful. Use ## for section headers.",
  },
  "arab-spring": {
    title: "The Arab Spring",
    minutes: 6,
    category: "History",
    prompt: "Explain the Arab Spring to a 16-year-old. Cover what triggered it, which countries were affected, successes and failures, Syria's civil war, and what it tells us about democracy and social media. Use ## for section headers.",
  },
  "residential-schools": {
    title: "Residential Schools in Canada",
    minutes: 7,
    category: "History",
    prompt: "Explain residential schools in Canada to a 16-year-old. Cover the system's purpose, conditions, cultural genocide, survivor testimonies, the TRC, and ongoing impacts on Indigenous communities today. Be factual and respectful. Use ## for section headers.",
  },
  "vietnam-war": {
    title: "The Vietnam War and Its Legacy",
    minutes: 6,
    category: "History",
    prompt: "Explain the Vietnam War to a 16-year-old. Cover the Cold War context, US involvement, Canada's role as draft dodger refuge, the fall of Saigon, and its political legacy. Use ## for section headers.",
  },
  "cuban-missile-crisis": {
    title: "The Cuban Missile Crisis",
    minutes: 5,
    category: "History",
    prompt: "Explain the Cuban Missile Crisis to a 16-year-old. Cover the standoff, how close the world came to nuclear war, Canada's role, and lessons for nuclear diplomacy today. Use ## for section headers.",
  },
  "colonialism-modern-world": {
    title: "How Colonialism Shaped the Modern World",
    minutes: 7,
    category: "History",
    prompt: "Explain how colonialism shaped the modern world to a 16-year-old. Cover European expansion, exploitation systems, borders drawn by colonizers, independence movements, and ongoing economic effects. Use ## for section headers.",
  },
};

export default async function LearnModule({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const module = MODULE_MAP[slug];
  if (!module) notFound();
  return <LearnModuleClient module={module} slug={slug} />;
}