import { notFound } from "next/navigation";
import LearnModuleClient from "./LearnModuleClient";

const MODULE_MAP: Record<string, { title: string; prompt: string; minutes: number; category: string }> = {
  "how-ontarios-legislature-works": {
    title: "How Ontario's Legislature Works",
    minutes: 5,
    category: "Systems",
    prompt: "Explain how Ontario's provincial legislature works to a 16-year-old Canadian student. Cover: what the Legislative Assembly is, how MPPs are elected, how laws get passed, and why it matters to everyday life. Be specific to Ontario. Write in clear sections with headers.",
  },
  "ontarios-tax-system": {
    title: "Ontario's Tax System Explained",
    minutes: 5,
    category: "Systems",
    prompt: "",
  },
  "municipal-government": {
    title: "How Municipal Government Works",
    minutes: 4,
    category: "Systems",
    prompt: "",
  },
  "charter-of-rights": {
    title: "What is the Charter of Rights?",
    minutes: 5,
    category: "Systems",
    prompt: "",
  },
  "what-is-anarchism": {
    title: "What is Anarchism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "",
  },
  "what-is-fascism": {
    title: "What is Fascism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "",
  },
  "what-is-social-democracy": {
    title: "What is Social Democracy?",
    minutes: 4,
    category: "Ideologies",
    prompt: "",
  },
  "jagmeet-singh": {
    title: "Jagmeet Singh and the NDP",
    minutes: 5,
    category: "Figures",
    prompt: "",
  },
  "karl-marx": {
    title: "Karl Marx: Ideas and Legacy",
    minutes: 6,
    category: "Figures",
    prompt: "",
  },
  "nelson-mandela": {
    title: "Nelson Mandela and Justice",
    minutes: 6,
    category: "Figures",
    prompt: "",
  },
  "malala-yousafzai": {
    title: "Malala Yousafzai and Education Rights",
    minutes: 5,
    category: "Figures",
    prompt: "",
  },
  "what-does-an-mpp-actually-do": {
    title: "What Does an MPP Actually Do?",
    minutes: 4,
    category: "Systems",
    prompt: "Explain what a Member of Provincial Parliament (MPP) does in Ontario to a 16-year-old. Cover their daily responsibilities, how they represent constituents, how they vote on bills, and how to contact yours. Be specific and practical.",
  },
  "how-a-bill-becomes-law": {
    title: "How a Bill Becomes Law",
    minutes: 5,
    category: "Systems",
    prompt: "Explain step by step how a bill becomes a law in Ontario's provincial legislature. Use a real recent Ontario bill as an example. Write for a 16-year-old, be specific and clear.",
  },
  "what-is-capitalism": {
    title: "What is Capitalism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain capitalism to a 16-year-old Canadian student. Cover: core principles, how it works in practice, its strengths and criticisms, and how it shapes Ontario's economy today. Present it fairly — show both what supporters and critics say.",
  },
  "what-is-socialism": {
    title: "What is Socialism?",
    minutes: 5,
    category: "Ideologies",
    prompt: "Explain socialism to a 16-year-old Canadian student. Cover: core principles, different forms of socialism, real world examples, strengths and criticisms. Present it fairly — show both what supporters and critics say. Include Canadian context.",
  },
  "che-guevara": {
    title: "Che Guevara: Revolutionary or War Criminal?",
    minutes: 7,
    category: "Figures",
    prompt: "Write a balanced profile of Che Guevara for a 16-year-old. Cover his early life, role in the Cuban Revolution, his ideology, the executions he ordered, his legacy, and why people still debate him today. Do not glorify or condemn — present the full picture with evidence.",
  },
  "tommy-douglas": {
    title: "Tommy Douglas and Canadian Healthcare",
    minutes: 5,
    category: "Figures",
    prompt: "Write a profile of Tommy Douglas for a 16-year-old Canadian student. Cover his background, how he brought public healthcare to Saskatchewan, his role in creating Medicare, and his lasting impact on Canada. Include why some opposed him and why he's still relevant today.",
  },
  "provincial-vs-federal-power": {
  title: "Provincial vs Federal Power",
  minutes: 6,
  category: "Systems",
  prompt: "Explain the difference between provincial and federal government powers in Canada to a 16-year-old. Use Ontario as the example. Cover what each level controls, why it matters, and real examples of conflicts between them. Use ## for section headers.",
},
"how-ontarios-budget-works": {
  title: "How Ontario's Budget Works",
  minutes: 7,
  category: "Systems",
  prompt: "Explain how Ontario's provincial budget works to a 16-year-old. Cover how it's made, what it funds, how to read it, and why it affects everyday life. Use ## for section headers.",
},
"what-is-liberalism": {
  title: "What is Liberalism?",
  minutes: 4,
  category: "Ideologies",
  prompt: "Explain liberalism to a 16-year-old Canadian student. Cover core principles, classical vs modern liberalism, Canadian examples, strengths and criticisms. Present both supporter and critic views fairly. Use ## for section headers.",
},
"what-is-conservatism": {
  title: "What is Conservatism?",
  minutes: 4,
  category: "Ideologies",
  prompt: "Explain conservatism to a 16-year-old Canadian student. Cover core principles, different types, Canadian examples, strengths and criticisms. Present both supporter and critic views fairly. Use ## for section headers.",
},
"what-is-marxism": {
  title: "What is Marxism?",
  minutes: 6,
  category: "Ideologies",
  prompt: "Explain Marxism to a 16-year-old Canadian student. Cover Marx's core ideas, historical applications, why it attracts supporters, and its criticisms. Present it fairly without glorifying or dismissing. Use ## for section headers.",
},
"what-is-libertarianism": {
  title: "What is Libertarianism?",
  minutes: 5,
  category: "Ideologies",
  prompt: "Explain libertarianism to a 16-year-old Canadian student. Cover core principles, economic and social libertarianism, Canadian context, strengths and criticisms. Present both supporter and critic views fairly. Use ## for section headers.",
},
"pierre-trudeau": {
  title: "Pierre Trudeau and the Charter",
  minutes: 6,
  category: "Figures",
  prompt: "Write a profile of Pierre Trudeau for a 16-year-old Canadian student. Cover his background, major policies, the Charter of Rights and Freedoms, controversies like the War Measures Act, and his lasting impact on Canada. Use ## for section headers.",
},
"margaret-thatcher": {
  title: "Margaret Thatcher and Neoliberalism",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Margaret Thatcher for a 16-year-old. Cover her background, economic policies, privatization, the Falklands War, her legacy, and why she's still debated today. Present both supporter and critic views. Use ## for section headers.",
},
"doug-ford": {
  title: "Doug Ford: Policies and Controversies",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Doug Ford as Ontario Premier for a 16-year-old. Cover his background, major policies, controversies like Greenbelt, education cuts, healthcare changes, and how different Ontarians view him. Present both supporter and critic views fairly. Use ## for section headers.",
},
"donald-trump": {
  title: "Donald Trump: Rise and Impact",
  minutes: 7,
  category: "Figures",
  prompt: "Write a balanced profile of Donald Trump for a 16-year-old. Cover his background, 2016 and 2024 election wins, major policies, controversies, and how he changed American politics. Present both supporter and critic views fairly. Use ## for section headers.",
},
"barack-obama": {
  title: "Barack Obama and American Politics",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Barack Obama for a 16-year-old. Cover his background, major policies like the ACA, foreign policy, his historic significance, and criticisms. Present both supporter and critic views. Use ## for section headers.",
},
"justin-trudeau": {
  title: "Justin Trudeau: Legacy and Criticism",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Justin Trudeau for a 16-year-old Canadian student. Cover his time as PM, major policies, controversies like SNC-Lavalin and blackface, his resignation, and how Canadians view his legacy. Use ## for section headers.",
},
"angela-merkel": {
  title: "Angela Merkel and European Leadership",
  minutes: 5,
  category: "Figures",
  prompt: "Write a balanced profile of Angela Merkel for a 16-year-old. Cover her background, 16 years as German Chancellor, refugee policy, European leadership, and her legacy. Use ## for section headers.",
},
"fidel-castro": {
  title: "Fidel Castro: Cuba's Controversial Leader",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Fidel Castro for a 16-year-old. Cover his revolution, communist Cuba, human rights record, US relations, and why he's still debated today. Present both supporter and critic views. Use ## for section headers.",
},
"mahatma-gandhi": {
  title: "Gandhi and Non-Violent Resistance",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Mahatma Gandhi for a 16-year-old. Cover his methods of non-violent resistance, Indian independence, his views on caste, and his global legacy. Use ## for section headers.",
},
"martin-luther-king": {
  title: "Martin Luther King Jr. and Civil Rights",
  minutes: 6,
  category: "Figures",
  prompt: "Write a profile of Martin Luther King Jr. for a 16-year-old. Cover the Civil Rights Movement, his methods, major speeches, FBI surveillance, assassination, and lasting impact. Use ## for section headers.",
},
"aoc": {
  title: "Alexandria Ocasio-Cortez and Progressive Politics",
  minutes: 5,
  category: "Figures",
  prompt: "Write a balanced profile of Alexandria Ocasio-Cortez for a 16-year-old. Cover her background, Green New Deal, democratic socialism, impact on the Democratic Party, and criticisms. Use ## for section headers.",
},
"winston-churchill": {
  title: "Winston Churchill: Hero or Villain?",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Winston Churchill for a 16-year-old. Cover WWII leadership, the Bengal famine, colonial policies, and why historians still debate his legacy. Present both sides fairly. Use ## for section headers.",
},
"vladimir-putin": {
  title: "Vladimir Putin and Russian Power",
  minutes: 6,
  category: "Figures",
  prompt: "Write a balanced profile of Vladimir Putin for a 16-year-old. Cover his rise to power, political system, Ukraine invasion, human rights record, and how Russians vs the West view him. Use ## for section headers.",
},
"supreme-court": {
  title: "How the Supreme Court Works",
  minutes: 5,
  category: "Systems",
  prompt: "Explain how Canada's Supreme Court works to a 16-year-old. Cover how judges are appointed, how cases reach the court, landmark Canadian rulings, and why it matters. Use ## for section headers.",
},
"notwithstanding-clause": {
  title: "What is the Notwithstanding Clause?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain the notwithstanding clause (Section 33 of the Charter) to a 16-year-old. Cover what it does, how Ontario and Quebec have used it, the debate around it, and why it matters. Use ## for section headers.",
},
"ontario-healthcare-system": {
  title: "How Ontario's Healthcare System Works",
  minutes: 6,
  category: "Systems",
  prompt: "Explain how Ontario's healthcare system works to a 16-year-old. Cover OHIP, what's covered and what isn't, how hospitals are funded, current challenges, and the privatization debate. Use ## for section headers.",
},
"what-is-lobbying": {
  title: "What is Lobbying?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain lobbying to a 16-year-old Canadian student. Cover what lobbyists do, Ontario examples, why it's legal, arguments for and against, and how it affects policy. Use ## for section headers.",
},
"media-and-politics": {
  title: "How Media Shapes Politics",
  minutes: 5,
  category: "Systems",
  prompt: "Explain how media shapes politics to a 16-year-old. Cover traditional vs social media, media bias, the Ontario media landscape, misinformation, and how to be a critical news consumer. Use ## for section headers.",
},
"gerrymandering": {
  title: "What is Gerrymandering?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain gerrymandering to a 16-year-old. Cover how it works, US vs Canadian examples, why Canada is less affected, and why electoral boundaries still matter. Use ## for section headers.",
},
"political-parties": {
  title: "How Political Parties Work",
  minutes: 5,
  category: "Systems",
  prompt: "Explain how political parties work in Ontario and Canada to a 16-year-old. Cover party structure, how leaders are chosen, party platforms, whipped votes, and Ontario's main parties. Use ## for section headers.",
},
"what-is-referendum": {
  title: "What is a Referendum?",
  minutes: 4,
  category: "Systems",
  prompt: "Explain what a referendum is to a 16-year-old. Cover how they work in Canada, examples like Quebec and electoral reform votes, pros and cons of direct democracy. Use ## for section headers.",
},
"federal-government": {
  title: "How Canada's Federal Government Works",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain how Canada's federal government works to a 16-year-old. Cover the House of Commons, Senate, Governor General, how laws are passed, and how it differs from provincial government. Use ## for section headers.",
},
"prime-minister-role": {
  title: "What Does the Prime Minister Actually Do?",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain what Canada's Prime Minister actually does to a 16-year-old. Cover their powers, limits, Cabinet, relationship with Parliament, and how they compare to a US President. Use ## for section headers.",
},
"canadas-senate": {
  title: "Canada's Senate: What's the Point?",
  minutes: 4,
  category: "Canada & World",
  prompt: "Explain Canada's Senate to a 16-year-old. Cover how senators are appointed, what they do, controversies like the expenses scandal, and the debate over abolishing or reforming it. Use ## for section headers.",
},
"first-nations-politics": {
  title: "First Nations and Canadian Politics",
  minutes: 7,
  category: "Canada & World",
  prompt: "Explain the relationship between First Nations and Canadian politics to a 16-year-old. Cover treaties, residential schools, land rights, UNDRIP, current political issues, and reconciliation. Be respectful and factual. Use ## for section headers.",
},
"canada-immigration": {
  title: "Canada's Immigration System",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain Canada's immigration system to a 16-year-old. Cover the points system, refugee claims, temporary workers, Ontario's demographics, and the current political debate around immigration levels. Use ## for section headers.",
},
"united-nations": {
  title: "The UN: What Does It Actually Do?",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain the United Nations to a 16-year-old. Cover its structure, what it actually does vs what people think it does, its failures and successes, and Canada's role. Use ## for section headers.",
},
"nato-canada": {
  title: "NATO and Why Canada Is In It",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain NATO to a 16-year-old Canadian student. Cover what it is, why Canada joined, the 2% spending debate, Russia-Ukraine context, and arguments for and against Canadian membership. Use ## for section headers.",
},
"canadian-elections": {
  title: "How Elections Work in Canada",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain how Canadian federal and provincial elections work to a 16-year-old. Cover the first-past-the-post system, why parties with fewer votes can win, voter turnout, and how to vote when you turn 18. Use ## for section headers.",
},
"commonwealth": {
  title: "What is the Commonwealth?",
  minutes: 4,
  category: "Canada & World",
  prompt: "Explain the Commonwealth of Nations to a 16-year-old Canadian student. Cover what it is, its colonial origins, what it does today, Canada's role, and whether it's still relevant. Use ## for section headers.",
},
"canada-us-relations": {
  title: "Canada-US Relations Explained",
  minutes: 5,
  category: "Canada & World",
  prompt: "Explain Canada-US relations to a 16-year-old. Cover trade, CUSMA, border issues, cultural influence, Trump-era tensions, and why the relationship is both essential and complicated. Use ## for section headers.",
},
"what-is-colonialism": {
  title: "What is Colonialism?",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain colonialism to a 16-year-old Canadian student. Cover what it is, British and French colonialism in Canada, its lasting effects on Indigenous peoples and global south, and why it's still relevant today. Use ## for section headers.",
},
"israel-palestine": {
  title: "The Israeli-Palestinian Conflict",
  minutes: 7,
  category: "Canada & World",
  prompt: "Explain the Israeli-Palestinian conflict to a 16-year-old. Cover the history, key events, both sides' perspectives, Canada's position, and why it's so divisive. Be strictly factual and balanced — do not take sides. Use ## for section headers.",
},
"russia-ukraine": {
  title: "Russia-Ukraine War: Background",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain the Russia-Ukraine war to a 16-year-old Canadian student. Cover historical background, why Russia invaded, Ukraine's response, Canada's involvement, and the global impact. Be factual and balanced. Use ## for section headers.",
},
"china-politics": {
  title: "China's Political System",
  minutes: 6,
  category: "Canada & World",
  prompt: "Explain China's political system to a 16-year-old. Cover the Communist Party structure, how it differs from Western democracy, economic model, human rights issues, and Canada-China relations. Use ## for section headers.",
},
"what-is-g7": {
  title: "What is the G7?",
  minutes: 4,
  category: "Canada & World",
  prompt: "Explain the G7 to a 16-year-old Canadian student. Cover what it is, who's in it, what it does, Canada's role, and criticisms of it. Use ## for section headers.",
},
"climate-change-politics": {
  title: "Climate Change and Politics",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the politics of climate change to a 16-year-old Canadian student. Cover the science consensus, carbon tax debate, Ontario's policies, international agreements, and left vs right perspectives. Use ## for section headers.",
},
"universal-basic-income": {
  title: "What is Universal Basic Income?",
  minutes: 5,
  category: "Issues",
  prompt: "Explain Universal Basic Income to a 16-year-old. Cover what it is, Ontario's pilot program, arguments for and against, cost concerns, and political positions. Use ## for section headers.",
},
"drug-policy-canada": {
  title: "Drug Policy in Canada",
  minutes: 5,
  category: "Issues",
  prompt: "Explain drug policy in Canada to a 16-year-old. Cover cannabis legalization, opioid crisis, decriminalization debate, harm reduction, and different political positions. Use ## for section headers.",
},
"gun-control": {
  title: "Gun Control: Canada vs US",
  minutes: 5,
  category: "Issues",
  prompt: "Explain the gun control debate to a 16-year-old, comparing Canada and the US. Cover Canadian laws, recent changes, the US Second Amendment, and why the debate differs so much between the two countries. Use ## for section headers.",
},
"abortion-rights": {
  title: "Abortion Rights and Politics",
  minutes: 6,
  category: "Issues",
  prompt: "Explain abortion rights and politics to a 16-year-old. Cover Canada's legal status, how it differs from the US post-Roe, different moral and political positions, and the Ontario political landscape. Present all perspectives fairly. Use ## for section headers.",
},
"police-reform": {
  title: "Police Reform and Defunding Debate",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the police reform debate to a 16-year-old. Cover what defunding actually means, Ontario context, arguments for and against reform, race and policing data, and different political positions. Use ## for section headers.",
},
"free-speech": {
  title: "Free Speech vs Hate Speech",
  minutes: 5,
  category: "Issues",
  prompt: "Explain the free speech vs hate speech debate to a 16-year-old Canadian student. Cover Charter protections, what hate speech laws actually say, campus debates, online speech, and different political positions. Use ## for section headers.",
},
"income-inequality": {
  title: "Income Inequality in Ontario",
  minutes: 5,
  category: "Issues",
  prompt: "Explain income inequality in Ontario to a 16-year-old. Cover the data, causes, effects on daily life, what different political parties propose, and why it's gotten worse. Use ## for section headers.",
},
"healthcare-privatization": {
  title: "Healthcare Privatization Debate",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the healthcare privatization debate in Ontario to a 16-year-old. Cover what privatization means in this context, Doug Ford's changes, arguments for and against, and what's at stake. Use ## for section headers.",
},
"social-media-democracy": {
  title: "Social Media and Democracy",
  minutes: 5,
  category: "Issues",
  prompt: "Explain how social media affects democracy to a 16-year-old. Cover misinformation, echo chambers, political ads, TikTok and elections, and what Canada is doing about it. Use ## for section headers.",
},
"affirmative-action": {
  title: "What is Affirmative Action?",
  minutes: 5,
  category: "Issues",
  prompt: "Explain affirmative action to a 16-year-old. Cover what it is, US vs Canadian approaches, equity vs equality debate, arguments for and against, and Ontario context. Use ## for section headers.",
},
"prison-reform": {
  title: "Prison System and Reform",
  minutes: 6,
  category: "Issues",
  prompt: "Explain the prison system and reform debate to a 16-year-old Canadian student. Cover how Canadian prisons work, incarceration rates, Indigenous overrepresentation, rehabilitation vs punishment debate. Use ## for section headers.",
},
"rent-control": {
  title: "Rent Control Debate",
  minutes: 5,
  category: "Issues",
  prompt: "Explain the rent control debate to a 16-year-old Ontarian. Cover what rent control is, Ontario's rules, Doug Ford's 2018 changes, economist arguments against it, tenant arguments for it. Use ## for section headers.",
},
"minimum-wage-economics": {
  title: "Minimum Wage Economics",
  minutes: 5,
  category: "Issues",
  prompt: "Explain minimum wage economics to a 16-year-old. Cover Ontario's history, arguments for raising it, business arguments against, what the research actually says, and current political positions. Use ## for section headers.",
},
"electoral-reform": {
  title: "Electoral Reform in Canada",
  minutes: 5,
  category: "Issues",
  prompt: "Explain electoral reform in Canada to a 16-year-old. Cover first-past-the-post, proportional representation, Trudeau's broken promise, Ontario's 2007 referendum, and arguments for and against change. Use ## for section headers.",
},
};

export default async function LearnModule({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const module = MODULE_MAP[slug];
  if (!module) notFound();
  return <LearnModuleClient module={module} slug={slug} />;
}